# Generated by Django 5.1.1 on 2024-10-01 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('setor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ocupações',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('data_fim', models.DateField()),
                ('hora_fim', models.TimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('data_fim', models.DateField()),
                ('hora_fim', models.TimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evento')),
            ],
            options={
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(max_length=20)),
                ('palestrante', models.CharField(max_length=50)),
                ('duracao', models.TimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evento')),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
