# Generated by Django 5.1.1 on 2024-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='referencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
