# Generated by Django 5.1.2 on 2024-11-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_local_link_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='palestrante',
        ),
    ]
