# Generated by Django 5.1.2 on 2024-11-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_feedback_duracao_remove_feedback_palestrante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
