# Generated by Django 5.1.2 on 2024-11-05 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
